ENH: Add action for fetching the CheckV database
bokulich-lab/q2-viromics pull request #6
Opened 2024-07-10 10:57 UTC by ChristosMatzoros

This PR closes #2  .

- Adds action to fetch CheckC database.

### Set up the environment
 ```shell
mamba create -n q2-viromics -c conda-forge -c bioconda -c https://packages.qiime2.org/qiime2/2024.10/metagenome/passed/ -c defaults q2cli q2-types checkv pyhmmer
```

###  Activate q2-viromics environment
```shell
conda activate q2-viromics
```

### Clone the repo and checkout the PR branch
```bash
git clone https://github.com/bokulich-lab/q2-viromics.git
cd q2-viromics
git fetch origin pull/4/head:pr-4
git checkout pr-4
pip install -e .
```

### 1. Download initial  CheckV database directory
[here](https://polybox.ethz.ch/index.php/s/X7dRSgqpAOLvt9C)

### 2. Test it out!

### Import database
```bash
# It may take some time!
qiime tools import --type 'CheckVDb' --input-path db --output-path checkv_db.qza
```

2024-07-11 08:51 UTC, VinzentRisch requested changes
Hi see some changes and questions below.

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +
Why is this here? You are not using this function. It looks like you copied it from another plugin. 
Also whats wrong with just using `os.path.abspath(file_name)` directly?

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +
Same here why do you have this? You are not using it.
this is also the same as just using `os.makedirs(path, exists_ok: True)`

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +
Same with this it is not used anywhere in the plugin.

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +
Same here

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +
Also this one is not used

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_utils.py
> +    return os.path.basename(fp).rsplit("_contigs.fa", maxsplit=1)[0]
This is also not used.

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/_version.py
Why do you need this file?
I mean you did not write this yourself, right?
Why not import it somehow?

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/checkv_fetch_db.py
> +    # Initialize a directory format object to store the Minimap2 index
```suggestion
    # Initialize a directory format object to store the CheckV database
```

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/checkv_fetch_db.py
> +    # Construct the command to build the Minimap2 index file
```suggestion
    # Construct the command to download the CheckV database
```

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/checkv_fetch_db.py
> +# Fetch the Virsorter2 database
```suggestion
# Fetch the CheckV database
```

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/types/_type.py
> +CheckVDb = SemanticType("CheckVDb")
```suggestion
CheckVDB = SemanticType("CheckVDB")
```

2024-07-11 08:51 UTC, VinzentRisch commented on q2_viromics/tests/data/type/db/checkVdb/hmm_db/checkv_hmms/1.hmm
Your plugin is 76.2 Mb big and 76.1 are just database files.
See how you can reduce this. Most of it is unnecessary. Like having 3 hmm files, one would be enough. Also maybe find a way to make the files smaller. They dont have to be the original files for testing purposes.

2024-07-11 10:52 UTC, ChristosMatzoros commented on q2_viromics/tests/data/type/db/checkVdb/hmm_db/checkv_hmms/1.hmm
I will reduce these files.

2024-07-12 10:21 UTC, ChristosMatzoros commented
Hello @VinzentRisch, I made the requested changes. You can have a look.

2024-07-15 13:24 UTC, VinzentRisch requested changes
Hi looks good! just fix the path maker tests.

2024-07-15 13:24 UTC, VinzentRisch commented on q2_viromics/tests/test_format.py
> +        self.assertEqual(result, "/dummy/path/hmm/dir/name.hmm")
You have to explicitly state the parameters
```suggestion
    @patch.object(CheckVDBDirFmt, "hmm_files_path_maker")
    def test_hmm_files_path_maker(self, mock_hmm_files):
        mock_hmm_files.return_value = "/dummy/path/hmm/dir/name.hmm"
        result = self.format.hmm_files_path_maker(outer="outer", dir="dir", name="name")
        mock_hmm_files.assert_called_once_with("outer", "dir", "name")
        self.assertEqual(result, "/dummy/path/hmm/dir/name.hmm")
```

2024-07-15 14:41 UTC, ChristosMatzoros commented
@VinzentRisch I did the changes in the unittests.

2024-07-15 15:20 UTC, VinzentRisch approved these changes
Looks good! feel free to merge

2024-07-15 18:02 UTC, merged